### ISSUE TITLE
Add support for latest vagrant versions

### ISSUE THREAD

**Issue by enver** [fjsanpedro/vagrant-node#7]
As of vagrant version v1.6.0 lib/vagrant/environment.rb does not have member lock_path causing crash on vagrant nodeserver \* commands:

```
$ vagrant nodeserver start
/home/personal/.vagrant.d/gems/gems/vagrant-node-0.0.2/lib/vagrant-node/nodeserverstart.rb:17:in `execute': undefined method `lock_path' for #<Vagrant::Environment: /home/personal/git/operations> (NoMethodError)
    from /home/personal/.vagrant.d/gems/gems/vagrant-node-0.0.2/lib/vagrant-node/nodeservercommand.rb:43:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

**Comment by stefangeorg** [comment]
#ServerAPI::ServerManager.run(File.dirname(@env.lock_path),@env.data_dir,argv[0].to_i)
ServerAPI::ServerManager.run(File.dirname('/tmp'),@env.data_dir,argv[0].to_i)

to get it to run
